### ISSUE TITLE
导出过程提示ValueError: Row numbers must be between 1 and 1048576. Row number supplied was 1048577

### ISSUE THREAD

**Issue by 3CB3EC** [aoguai/QQtoExcel#10]
完整报错内容：

—————————————————欢迎使用———————————————————
——————————————QQtoExcelV1.8————————————————
项目地址：https://github.com/aoguai/QQtoExcel

请输入您导出的聊天记录txt路径（支持单好友、群聊与[全部消息记录.txt]）：C:\Users\admin\Desktop\ch.txt
请输入您转换后欲保存的目录（留空则默认保存在out目录中）：
请输入工作表名（留空则默认[消息对象]）：
请输入文件命名规则（留空则使用默认规则）：
是否导出时间（留空则默认Y）（Y/N）：
是否导出昵称（留空则默认Y）（Y/N）：
是否导出uid（留空则默认Y）（Y/N）：
是否导出内容（留空则默认Y）（Y/N）：
是否按好友导出（留空则默认Y）（Y/N）：
是否过滤无意义内容（留空则默认N）（Y/N）：
是否自定义可选项标题（留空则默认N）（Y/N）：
是否需要多工作表导出（留空则默认N）（Y/N）：
我加入的群聊 消息分组导出中:   0%|                                                               | 0/1 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "releases.py", line 93, in <module>
  File "QQtoExcel.py", line 344, in toExcel
  File "QQtoExcel.py", line 327, in _create_excel_file
  File "QQtoExcel.py", line 325, in write_data_to_worksheet
  File "openpyxl\worksheet\worksheet.py", line 245, in cell
  File "openpyxl\worksheet\worksheet.py", line 258, in _get_cell
ValueError: Row numbers must be between 1 and 1048576. Row number supplied was 1048577
[74920] Failed to execute script 'releases' due to unhandled exception!

应该是excel软件单页不能超过1048577行，我这只导出了一个群的消息，看来数据量大了以后还是怕的😂

希望能够尽快推出导出文件是纯csv的版本

**Comment by aoguai** [comment]
研究了一下，现在的代码太💩山了。更新修复肯定是会修的。

如果您着急，一个临时的解决办法是：可以手动打开txt手动分割一下。

不着急可以等等更新。

**Comment by 3CB3EC** [comment]
> 研究了一下，现在的代码太💩山了。更新修复肯定是会修的。
> 
> 如果您着急，一个临时的解决办法是：可以手动打开txt手动分割一下。
> 
> 不着急可以等等更新。

没事不着急，有的免费用就不错了

**Comment by aoguai** [comment]
试试新版解决了没

https://github.com/aoguai/QQtoExcel/releases/tag/v1.9.0

**Comment by 3CB3EC** [comment]
> 试试新版解决了没
> 
> https://github.com/aoguai/QQtoExcel/releases/tag/v1.9.0

新版有一点小BUG，导出csv的时候，昵称那一个字段多了一个换行符，其他没有什么问题，谢谢

**Comment by aoguai** [comment]
> 新版有一点小BUG，导出csv的时候，昵称那一个字段多了一个换行符，其他没有什么问题，谢谢

好的好的，感谢🙏🏻

换行符bug已在最新提交 [65ecd7c](https://github.com/aoguai/QQtoExcel/commit/65ecd7c65473cc90376a0090744a02dd8ad90128) 解决，下个版本再更新吧。
