### ISSUE TITLE
win11 1.90 使用releases.exe调出命令行后输入完要求后闪退

### ISSUE THREAD

**Issue by Who-is-I** [aoguai/QQtoExcel#11]
- [ ] 是否查看wiki、issues后自己尝试解决

**描述错误**

简明扼要地描述该错误是什么。

**重现**

- [ ] 是否能重现

如果可以，重现该BUG的步骤是：
1. 
2. 
3.

**预期的效果**

简明扼要地描述你原来希望的效果。

**截图**

如果可以，添加截图以帮助解释你的问题。

**系统信息**

 - 操作系统: [例如.Windows]
 - 软件版本 [例如. V1.6]

**额外的信息**

在此添加关于问题的任何其他背景、猜想、推断。

**Comment by aoguai** [comment]
请尝试使用cmd进行操作避免闪退后提供报错信息。
具体操作是。
win+r 输入 cmd。
然后使用控制台 `cd releases.exe所在目录` 并运行 ``releases.exe`

**Comment by Who-is-I** [comment]
开发者您好，具体报错如下






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aoguai/QQtoExcel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月20日(星期六) 中午12:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aoguai/QQtoExcel] win11 1.90 使用releases.exe调出命令行后输入完要求后闪退 (Issue #11)





 
请尝试使用cmd进行操作避免闪退后提供报错信息。
 具体操作是。
 win+r 输入 cmd。
 然后使用控制台 cd releases.exe所在目录 并运行 ``releases.exe`

**Comment by aoguai** [comment]
#12
