### ISSUE TITLE
在命令行输入要求后闪退

### ISSUE THREAD

**Issue by Who-is-I** [aoguai/QQtoExcel#12]
100%重现
在命令行输入要求后闪退

 - 操作系统: [例如.Win11专业版 24H2]
 - 软件版本 [例如. V1.9]

**Comment by aoguai** [comment]
请尝试使用cmd进行操作避免闪退后提供报错信息。
具体操作是：
win+r 输入 cmd。
然后使用控制台 cd releases.exe所在目录 并运行 ``releases.exe`
![image](https://github.com/user-attachments/assets/0229ae72-6c72-4d44-ae87-2999df0b1200)

没有报错信息我只能帮你算一卦

**Comment by Who-is-I** [comment]
抱歉，由于网络问题，我不知道我的第一个提议是否发出去![屏幕截图 2024-07-20 123444.png](https://github.com/user-attachments/assets/2fa5239c-0107-4fe7-a06e-79700008ff91)

**Comment by aoguai** [comment]
看起来像错误产生的原因是文件无法打开，可能产生的原因是文件找不到，或者被占用，或者无权限访问

请尝试如下：
1.检查对应路径下的文件是否存在，且被占用。如果文件不存在，就找到对应文件即可；如果文件存在，被占用，将占用程序暂时关闭。
2.修改cmd的权限，以管理员身份运行：`wind + r,输入“cmd”,按 ctrl + shift + enter 以管理员权限打开`

如果以管理员权限运行还有报错，请继续上传截图

**Comment by Who-is-I** [comment]
这一次是管理员权限![屏幕截图 2024-07-20 125549.png](https://github.com/user-attachments/assets/b3c0c8c8-ba07-49ff-b084-78d2350cbbff)

**Comment by aoguai** [comment]
你输入的路径怎么是个文件夹，你应该输入聊天记录txt路径。
