### ISSUE TITLE
导出结果Excel打开报错

### ISSUE THREAD

**Issue by AbyssShang** [aoguai/QQtoExcel#3]
![image](https://user-images.githubusercontent.com/110171545/182618842-095bdade-4c0d-458a-b7a3-9431096b28bc.png)
导出文件使用Excel打开错误如上
Office版本：Microsoft 365MSO (版本 2206 Build 16.0.15330.20260) 64 位
操作系统：
  版本	Windows 11 专业工作站版
  版本	22H2
  操作系统版本	22622.440
  体验	Windows Feature Experience Pack 1000.22634.1000.0

**Comment by aoguai** [comment]
是这样的，你试试选择 “是” 能否继续正常看到内容，能看到就是正常的。

**Comment by AbyssShang** [comment]
将文件后缀改为".xlsx"，就能解决此问题

**Comment by aoguai** [comment]
感谢反馈，我看看下个版本再修复吧

**Comment by aoguai** [comment]
已在新版本修复
