### ISSUE TITLE
大佬请问你的QQ-G 手机QQ本地聊天记录查看器还在更新吗

### ISSUE THREAD

**Issue by lsrfsy** [aoguai/QQtoExcel#4]
吾爱找到的这个神器，ios端可以查看聊天记录，但是图片视频都是代码
![image](https://user-images.githubusercontent.com/83321611/210525628-6b78b196-6e61-4b7e-aa6b-eea9fd768f6c.png)

**Comment by lsrfsy** [comment]
> 吾爱找到的这个神器，ios端可以查看聊天记录，但是图片视频都是代码 ![image](https://user-images.githubusercontent.com/83321611/210525628-6b78b196-6e61-4b7e-aa6b-eea9fd768f6c.png)

大佬能更新一下最好了☺

**Comment by aoguai** [comment]
视频，图片是代码的原因是因为这些消息不是本地消息。近期没有更新这个软件的想法...因为有点吃力不讨好。抱歉抱歉。
您可以试一试这个项目：
https://github.com/Yiyiyimu/QQ-History-Backup

**Comment by lsrfsy** [comment]
> 视频，图片是代码的原因是因为这些消息不是本地消息。近期没有更新这个软件的想法...因为有点吃力不讨好。抱歉抱歉。 您可以试一试这个项目： https://github.com/Yiyiyimu/QQ-History-Backup

嗯，感谢，这个项目关注好久了，一直在等测试ios版
