### ISSUE TITLE
一个小小的报错

### ISSUE THREAD

**Issue by CatzTimes** [aoguai/QQtoExcel#5]
Traceback (most recent call last):
  File "releases.py", line 79, in <module>
  File "QQtoExcel.py", line 199, in toExcel
  File "QQtoExcel.py", line 86, in get_QQChat_record
PermissionError: [Errno 13] Permission denied: 'D:\\ceshi'
[18952] Failed to execute script 'releases' due to unhandled exception!

这个需要我怎么处理

**Comment by aoguai** [comment]
什么情况下出现的报错

**Comment by CatzTimes** [comment]
> 
![RSME1BL)MN(198RPFGXZ)%3](https://user-images.githubusercontent.com/62692767/213914435-a70bcabe-16cb-41ae-92cf-2ed48d5368be.png)

**Comment by aoguai** [comment]
![截图20230122195814](https://s2.loli.net/2023/01/22/jSvHP7qafwmK8Z9.png)
我这边刚测试一切正常，你是什么环境
看样子是打包出了问题，或者你有没有将压缩包全部解压后使用

**Comment by CatzTimes** [comment]
我已经全部解压的，但是我电脑上原本就有Python环境

**Comment by aoguai** [comment]
windows吗？

**Comment by CatzTimes** [comment]
是的 windows

**Comment by CatzTimes** [comment]
我觉得可能是缺什么模块？

**Comment by aoguai** [comment]
我测试了windows7和10都是没问题的，可能就是打包出问题了。你可以尝试直接运行代码或者试试CLI命令方式
