### ISSUE TITLE
在某个会话中，如果一条消息里面有回车换行，导出的数据就只会到回车换行的位置，导致最终数据导出不全

### ISSUE THREAD

**Issue by knowledgeeater** [aoguai/QQtoExcel#6]

**Comment by aoguai** [comment]
谢谢反馈，确实存在这种问题，但是目前没有较好的正则表达式匹配方案，我会尝试在以后的版本中修复

**Comment by aoguai** [comment]
已经在 [V1.7.0](https://github.com/aoguai/QQtoExcel/releases/tag/V1.7.0-20230519) 版本尝试修复
可以试试新版本
