### ISSUE TITLE
使用过程中不能out

### ISSUE THREAD

**Issue by Astrallee** [aoguai/QQtoExcel#7]
今天尝试了一下 不管是大文本还是小文本，都不能输出。如果采取命令行方法，会直接无输出报告完成。如果采取ui方法，一直停留在交界面，没有输出。

**Comment by aoguai** [comment]
检查一下是否您的聊天记录文本存在问题，如果不是，有没有运行截图提供一下。

**Comment by Astrallee** [comment]
![image](https://user-images.githubusercontent.com/48097779/224964341-66919d83-78bd-44ba-bcaf-6f3275915f89.png)
这个是文本图片

**Comment by Astrallee** [comment]
这个是pycharm运行图
![J1LDTONEVA8 3{{8LC4Z(YT](https://user-images.githubusercontent.com/48097779/224965549-e46112cc-1b5a-4c41-b791-65727f9c7bbd.png)

**Comment by aoguai** [comment]
![image](https://user-images.githubusercontent.com/34203474/224966412-d9656c16-be0e-433d-a912-59dde9ffcb99.png)
我这边测试一切正常，或许你可以试试最新的V1.6

**Comment by Astrallee** [comment]
下的就是最新的，我刚才重新试了一下最新的记录导出，发现没有问题。  就是不太清楚为什么以前旧的文本消息不行。 谢谢你！
