### ISSUE TITLE
对于到回车就会自动停的手动解决方法

### ISSUE THREAD

**Issue by 1226608** [aoguai/QQtoExcel#8]
用word打开txt,然后查找^p^p替换为^p就行了

**Comment by aoguai** [comment]
可能是个很棒的方法，但是我其实希望找到个不需要任何而外操作的方法，毕竟每多一道操作上手门槛就高一些。

**Comment by aoguai** [comment]
已经在 [V1.7.0](https://github.com/aoguai/QQtoExcel/releases/tag/V1.7.0-20230519) 版本尝试修复
可以试试新版本

**Comment by lvhailong** [comment]
我用这个方法将两个连续回车替换为一个回车后不但没有解决问题，反而导出的信息都混乱了，我使用的就是v1.7还是搞不定...

**Comment by aoguai** [comment]
> 我用这个方法将两个连续回车替换为一个回车后不但没有解决问题，反而导出的信息都混乱了，我使用的就是v1.7还是搞不定...

那只能等待修复了，因为聊天记录各式各样，正则表达式匹配很难完全覆盖。
