### ISSUE TITLE
导出不完全

### ISSUE THREAD

**Issue by melody942** [aoguai/QQtoExcel#9]
经对比，很多聊天记录未能连续导出，绝大部分都中断了，而且大部分只开始了一点点，没有发现原因

**Comment by melody942** [comment]
看了一下大概是回车且有空行

**Comment by aoguai** [comment]
是最新版吗？新版还是有问题的话，这只能等更好的正则出现了😥

[对于到回车就会自动停的手动解决方法](https://github.com/aoguai/QQtoExcel/issues/8#issue-1679584308)

**Comment by melody942** [comment]
是最新版。好的，期待更新
